name: wake_up_call
description: "A GPS-based alarm clock for buses and trains."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Google Maps
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.4

  # GPS Tracking
  geolocator: ^13.0.4

  # geocoding
  geocoding: ^3.0.0

  #places
  google_places_flutter: ^2.0.5

  # Route Drawing
  flutter_polyline_points: ^2.0.0

  # State Management
  provider: ^6.0.5

  # Audio for alarm sound
  audioplayers: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/alarm.mp3
